import java.util.*;
public class Q15SmallestOf3Num{
    public static void main(String[] args){
        Scanner sc =new Scanner(System.in);
        int a=sc.nextInt();
        int b=sc.nextInt();
        int c=ac.nextInt();
        if(a<b && a<c){
            System.out.println(a);
        }else if(b<c && b<a){
            System.out.println(b);
        }else{
            SYstem.out.println(c);
        }
    }
}